### ISSUE TITLE
Great Project and Idea

### ISSUE THREAD

**Issue by ramonck** [brutesque/docker-swarm-over-vpn-mesh#1]
Hi,

This is a great project, was wondering how I could add GCP for example and how can I set which type of instance I want?
What if I have multiple accounts in each provider can I setup multiple ssh keys or something?

Best Regards,

**Comment by brutesque** [comment]
Hello,

I personally don't use services like gcp and aws, but you should probably look into adding them to the terraform file named vps-instances.tf. Multiple accounts from the same provider should also be possible by editing the vps-instances.tf file.

**Comment by brutesque** [comment]
terraform-inventory.py might need some adjustments as well. That part is not as nicely dynamic yet as I'd like it to be. But it works well for me at the moment with my current requirements.
